---
services:
  ## Web Server / Reverse Proxy
  # Handles TLS termination using either Let's Encrypt or custom certificates
  caddy:
    image: ${IMAGE_CADDY:-lucaslorentz/caddy-docker-proxy:2.10.0-alpine}
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=frontend-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/caddy:/data/caddy"
    networks:
      - frontend-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:2019/metrics || exit 1"]
      start_period: 20s
      interval: 20s
      timeout: 5s
      retries: 3
    labels:
      # Expose per-host metrics on port 2020
      # Source: https://github.com/lucaslorentz/caddy-docker-proxy/issues/613
      caddy_0.metrics:
      caddy_0.metrics.per_host:
      caddy_1: ":2020"
      caddy_1.metrics: /metrics

networks:
  frontend-net:
    name: frontend-net
    enable_ipv6: ${ENABLE_IPV6:-true}
