services:
  dtable-server:
    image: ${DTABLE_SERVER_IMAGE:-}
    restart: unless-stopped
    container_name: dtable-server
    volumes:
      - /opt/seatable-server:/shared
      - type: bind
        source: ./seatable-license.txt
        target: /shared/seatable/seatable-license.txt
        read_only: ${SEATABLE_LICENSE_FORCE_READ_ONLY:-false}
        bind:
          create_host_path: false
    environment:
      - SEATABLE_MYSQL_DB_HOST=${MARIADB_HOST:-mariadb}
      - SEATABLE_MYSQL_DB_PORT=${MARIADB_PORT:-3306}
      - SEATABLE_MYSQL_DB_USER=root
      - SEATABLE_MYSQL_DB_PASSWORD=${MARIADB_PASSWORD:?Variable is not set or empty}
      - SEATABLE_MYSQL_DB_DTABLE_DB_NAME=dtable_db
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:?Variable is not set or empty}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - TZ=${TIME_ZONE:?Variable is not set or empty}
      - INNER_DTABLE_WEB_SERVICE_URL=${INNER_DTABLE_WEB_SERVICE_URL:-http://seatable-server:80}
      - INNER_DTABLE_DB_URL=${INNER_DTABLE_DB_URL:-http://seatable-server:7777}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      seatable-server:
        condition: service_healthy
    networks:
      - backend-seatable-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ping || exit 1"]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s
