---
services:
  ofelia:
    image: mcuadros/ofelia:0.3.18
    container_name: ofelia
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=${TIME_ZONE}
    depends_on:
      - seatable-server

  # Schedule the garbage collector to run once a week, overnight from Saturday to Sunday.
  seatable-server:
    labels:
      ofelia.enabled: "true"

      # clean /tmp directory
      ofelia.job-exec.clean-tmp.command: "find /tmp -type f -mtime +3 -delete"
      ofelia.job-exec.clean-tmp.schedule: "@weekly"
      
      # garbage collector
      ofelia.job-exec.gc.command: "/opt/seatable/scripts/seatable.sh gc --rm-fs | grep -E 'damaged|removed|finished'"
      ofelia.job-exec.gc.schedule: "@weekly"
      #ofelia.job-exec.gc.schedule: "0 15 3 * * *"  # ofeila v0.3 still requires seconds!
      
      # filesystem check
      ofelia.job-exec.seaf-fsck.command: "/opt/seatable/seatable-server-latest/seaf-fsck.sh | grep -E 'corrupted|damaged|missing|finished'"
      ofelia.job-exec.seaf-fsck.schedule: "@weekly"

      
