---
services:
  caddy:
    ports:
      - ${ONLYOFFICE_PORT:-6233}:${ONLYOFFICE_PORT:-6233}

  onlyoffice:
    image: ${ONLYOFFICE_IMAGE:-onlyoffice/documentserver:8.3.3.1}
    restart: unless-stopped
    container_name: onlyoffice
    environment:
      - JWT_ENABLED=${ONLYOFFICE_JWT_ENABLED:-true}
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET:?Variable is not set or empty}
    volumes:
      - /opt/onlyoffice/logs:/var/log/onlyoffice
      - /opt/onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/onlyoffice/lib:/var/lib/onlyoffice
    labels:
      caddy: ${SEATABLE_SERVER_HOSTNAME}:${ONLYOFFICE_PORT:-6233}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - frontend-net

networks:
  frontend-net:
    name: frontend-net
