---
services:
  python-scheduler:
    image: ${PYTHON_SCHEDULER_IMAGE:-seatable/seatable-python-scheduler:4.2.2}
    restart: unless-stopped
    container_name: python-scheduler
    environment:
      - TIME_ZONE=${TIME_ZONE}
      - DB_HOST=${SEATABLE_MYSQL_HOST:-mariadb}
      - DB_ROOT_PASSWD=${MARIADB_PASSWORD:?Variable is not set or empty}
      - PYTHON_SCHEDULER_AUTH_TOKEN=${PYTHON_SCHEDULER_AUTH_TOKEN:?Variable is not set or empty}
      - SEATABLE_SERVER_URL=${SEATABLE_SERVER_PROTOCOL:-https}://${SEATABLE_SERVER_HOSTNAME}
      - PYTHON_STARTER_URL=${PYTHON_STARTER_URL:-http://python-starter:8080}
      - PYTHON_SCHEDULER_LOG_LEVEL=${PYTHON_SCHEDULER_LOG_LEVEL:-WARNING}
      - DELETE_LOG_DAYS=${DELETE_LOG_DAYS:-30}
      # Timeout is defined in seconds
      - PYTHON_PROCESS_TIMEOUT=${PYTHON_PROCESS_TIMEOUT:-60}
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - LOG_TO_STDOUT=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend-net
      - backend-scheduler-net
      - backend-seatable-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pgrep -f 'python3 scheduler.py' && pgrep -f 'python3 flask_server.py'",
        ]
      interval: 20s
      retries: 3
      start_period: 20s
      timeout: 10s

  python-starter:
    image: ${PYTHON_STARTER_IMAGE:-seatable/seatable-python-starter:4.2.2}
    restart: unless-stopped
    container_name: python-starter
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}:${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}"
    environment:
      - PYTHON_SCHEDULER_URL=${PYTHON_SCHEDULER_URL:-http://python-scheduler}
      - PYTHON_TRANSFER_DIRECTORY=${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}
      - PYTHON_RUNNER_IMAGE=${PYTHON_RUNNER_IMAGE:-seatable/seatable-python-runner:4.2.2}
      - PYTHON_STARTER_LOG_LEVEL=${PYTHON_STARTER_LOG_LEVEL:-WARNING}
      - PYTHON_RUNNER_CONTAINER_CPUS=${PYTHON_RUNNER_CONTAINER_CPUS:-1}
      - PYTHON_RUNNER_CONTAINER_MEMORY=${PYTHON_RUNNER_CONTAINER_MEMORY:-1g}
      # Timeout is defined in seconds
      - PYTHON_PROCESS_TIMEOUT=${PYTHON_PROCESS_TIMEOUT:-60}
      - PYTHON_RUNNER_READ_ONLY_FILESYSTEM=${PYTHON_RUNNER_READ_ONLY_FILESYSTEM:-true}
      - PYTHON_RUNNER_TMPFS_MOUNT_SIZE_IN_BYTES=${PYTHON_RUNNER_TMPFS_MOUNT_SIZE_IN_BYTES:-104857600}
      - PYTHON_RUNNER_DROPPED_CAPABILITIES=${PYTHON_RUNNER_DROPPED_CAPABILITIES:-CAP_NET_RAW}
      - PYTHON_RUNNER_NO_NEW_PRIVILEGES=${PYTHON_RUNNER_NO_NEW_PRIVILEGES:-true}
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - LOG_TO_STDOUT=true
    networks:
      - backend-scheduler-net

  python-runner:
    image: ${PYTHON_RUNNER_IMAGE:-seatable/seatable-python-runner:4.2.2}
    restart: unless-stopped
    container_name: python-runner
    networks:
      # This is added to ensure that the runner-net network is created
      # Docker-Compose does not seem to create networks that are not used by any containers in the compose file(s)
      - runner-net

networks:
  frontend-net:
    name: frontend-net
  backend-scheduler-net:
    name: backend-scheduler-net
  # Network shared by all job containers
  runner-net:
    name: runner-net
    driver: bridge
    driver_opts:
      # Disable inter-container connectivity
      com.docker.network.bridge.enable_icc: "false"
