---
services:
  caddy:
    ports:
      - ${SEADOC_PORT:-7070}:${SEADOC_PORT:-7070}

  seadoc:
    image: ${SEADOC_IMAGE:-seafileltd/sdoc-server:2.0.1-testing}
    container_name: seadoc
    volumes:
      - ${SEADOC_VOLUME:-/opt/seadoc/}:/shared
    environment:
      - DB_HOST=${MARIADB_HOST:-mariadb}
      - DB_PORT=${MARIADB_PORT:-3306}
      - DB_USER=${MARIADB_USER:-root}
      - DB_PASSWORD=${MARIADB_ROOT_PASSWORD:?Variable is not set or empty}
      - DB_NAME=dtable_db
      - TIME_ZONE=${TIME_ZONE}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - NON_ROOT=${NON_ROOT:-false}
      - SEAHUB_SERVICE_URL=${SEATABLE_SERVER_PROTOCOL:-https}://${SEATABLE_SERVER_HOSTNAME:?Variable is not set or empty}
    labels:
      caddy: "${SEATABLE_SERVER_PROTOCOL:-https}://${SEATABLE_SERVER_HOSTNAME:?Variable is not set or empty}:${SEADOC_PORT:-7070}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    depends_on:
      - mariadb:
    networks:
      - frontend-net
      - backend-seatable-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/ping || exit 1"]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  frontend-net:
    name: frontend-net
  backend-seatable-net:
    name: backend-seatable-net
