---
services:

  seatable-ai:
    image: ${SEATABLE_AI_IMAGE:-seatable/seatable-ai:1.1.0-testing}
    container_name: seatable-ai
    volumes:
      - ${SEATABLE_AI_VOLUME:-/opt/seatable-server/}:/shared
    ports:
      - "8888:8888"
    environment:
      - TIME_ZONE=${TIME_ZONE:-Etc/UTC}
      - SEATABLE_MYSQL_DB_HOST=${SEATABLE_MYSQL_DB_HOST:?Variable is not set or empty}
      - SEATABLE_MYSQL_DB_PORT=${SEATABLE_MYSQL_DB_PORT:-3306}
      - SEATABLE_MYSQL_DB_USER=${SEATABLE_MYSQL_DB_USER:-seatable}
      - SEATABLE_MYSQL_DB_PASSWORD=${SEATABLE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - SEATABLE_MYSQL_DB_DTABLE_DB_NAME=${SEATABLE_MYSQL_DB_DTABLE_DB_NAME:-dtable_db}
      - REDIS_HOST=${REDIS_HOST:?Variable is not set or empty}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEATABLE_SERVER_URL=${SEATABLE_SERVER_PROTOCOL:-https}://${SEATABLE_SERVER_HOSTNAME:?Variable is not set or empty}
    networks:
      - backend-seatable-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8888 || exit 1"]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  backend-seatable-net:
    name: backend-seatable-net
