---
services:
  caddy:
    ports:
      - ${TLDRAW_PORT:-6239}:${TLDRAW_PORT:-6239}

  tldraw-worker:
    image: ${TLDRAW_IMAGE:-seatable/tldraw-worker:2.1.1}
    container_name: tldraw-worker
    restart: unless-stopped
    environment:
      - SEATABLE_SERVER_URL=${SEATABLE_SERVER_PROTOCOL:-https}://${SEATABLE_SERVER_HOSTNAME:?Variable is not set or empty}
    labels:
      caddy: ${SEATABLE_SERVER_HOSTNAME}:${TLDRAW_PORT:-6239}
      caddy.reverse_proxy: "{{upstreams 5858}}"
    networks:
      - frontend-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5858/ping || exit 1"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 5s
    logging:
      driver: json-file
      options:
        # Maximum size per file
        max-size: 10m
        # Maximum number of files
        max-file: 3
